### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by jsbean** [dn-m/Helper#7]
Called as `dn-m config`.

- [x] Create `README.md` (see: #9)
- [x] Create `.travis.yml` (see: #1)
- [x] Create `.hound.yml` (see: #3)
- [x] Create `.swiftlint.yml` (see: #4)
- [x] First, test presence of `Cartfile` 
- [x] Create `Cartfile` (see: #2)
- [x] Create `.gitignore` (see: #8)
